---
- name: Cau hinh tren router
  hosts: all
  gather_facts: no

  tasks:
    - name: run show version on remote devices
      cisco.iosxr.iosxr_command:
        commands:
          - show version
      register: output

    - debug: var=output.stdout_lines
